### PR TITLE
Test case that reproduces "too many open files" problem from #6.

### PR DESCRIPTION
**Pull request by mbooth101**
See bug #6

### CODE REVIEW

**Comment by michael-o** [comment]
Can you recheck your PR please?

**Comment by mbooth101** [comment]
@michael-o What do you mean? This PR was merged: https://github.com/codehaus-plexus/plexus-archiver/commit/92c0628f42e1ea6bb9611ca9181af38bf12d4d28

**Comment by michael-o** [comment]
I can close it?

**Comment by mbooth101** [comment]
I assume so, yes.

**Pull request closed without merging**
