### PR TITLE
detect permissions for addFile

### PR DESCRIPTION
**Pull request by hboutemy**
found while working on `maven-source-plugin` issue on `pom.properties` and `pom.xml`: https://issues.apache.org/jira/browse/MSOURCES-137
need to detect permission from file instead of blindly applying (unset) default file mode

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Can we add a test for it?

**Comment by hboutemy** [comment]
yes, that would be better than my manual tests inside maven-source-plugin: I have no idea, need to check how I can create such test, yes

**Comment by hboutemy** [comment]
@slawekjaranowski done

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
@hboutemy what label should we add for this? enhancement or bug?
A label is used by release drafter to categorize PR in release notes.

**Comment by hboutemy** [comment]
I'd say bug, as this API behaviour was not consistent with others

**Pull request merged**
